name: "Release a new version"

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - v1*

jobs:
  envs:
    name: envs
    steps:
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      # The github.ref is, for example, refs/tags/v1.0.52
      # Generate variables like:
      #   SRS_TAG=v1.0.52
      #   SRS_MAJOR=1
      # @see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Generate varaiables
        run: |
          SRS_TAG=$(echo ${{ github.ref }}| awk -F '/' '{print $3}')
          echo "SRS_TAG=$SRS_TAG" >> $GITHUB_ENV
          SRS_MAJOR=$(echo $SRS_TAG| cut -c 2)
          echo "SRS_MAJOR=$SRS_MAJOR" >> $GITHUB_ENV
      # Generate variables like:
      #   SRS_DROPLET_EIP=1.2.3.4
      - name: Build droplet variables
        run: |
          SRS_DROPLET_EIP=$(dig +short ossrs.net)
          echo "SRS_DROPLET_EIP=$SRS_DROPLET_EIP" >> $GITHUB_ENV
          SRS_DROPLET_EIP2=$(dig +short ossrs.io)
          echo "SRS_DROPLET_EIP2=$SRS_DROPLET_EIP2" >> $GITHUB_ENV
    outputs:
      SRS_DROPLET_EIP: ${{ env.SRS_DROPLET_EIP }}
      SRS_DROPLET_EIP2: ${{ env.SRS_DROPLET_EIP2 }}
      SRS_TAG: ${{ env.SRS_TAG }}
      SRS_MAJOR: ${{ env.SRS_MAJOR }}
    runs-on: ubuntu-20.04

  docker:
    name: docker
    needs:
      - envs
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      # Git checkout
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Push to docker hub
        run: |
          echo "Release ossrs/hgsw:$SRS_TAG"
          docker build --tag ossrs/hgsw:$SRS_TAG -f Dockerfile .
          docker tag ossrs/hgsw:$SRS_TAG ossrs/hgsw:$SRS_MAJOR
          docker push --all-tags ossrs/hgsw
    runs-on: ubuntu-20.04

  aliyun:
    name: aliyun-hub
    needs:
      - envs
      - docker
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
      - name: Login Aliyun docker hub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Docker copy images
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ossrs/hgsw:${{ env.SRS_TAG }}
          dst: |
            registry.cn-hangzhou.aliyuncs.com/ossrs/hgsw:${{ env.SRS_TAG }}
            registry.cn-hangzhou.aliyuncs.com/ossrs/hgsw:${{ env.SRS_MAJOR }}
    runs-on: ubuntu-20.04

  deploy:
    name: deploy ossrs.net
    needs:
      - envs
      - aliyun
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
          echo "SRS_DROPLET_EIP=${{ needs.envs.outputs.SRS_DROPLET_EIP }}" >> $GITHUB_ENV
      # Execute command in a ssh, because ufw limit the rate.
      - name: Restart the containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SRS_DROPLET_EIP }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          port: 22
          envs: SRS_TAG,SRS_MAJOR
          timeout: 60s
          command_timeout: 30m
          script: |
            # Allow access to container.
            ufw allow 1987
            #
            # Restart HGSW
            cat << END > /root/restart_docs-hgsw.sh
              # See https://github.com/winlinvip/http-gif-sls-writer
              docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/hgsw:$SRS_MAJOR
              docker rm -f docs-hgsw || sleep 1
              docker run -d -it --restart always \\
                -v /root/conf/hgsw.conf:/usr/local/etc/main.conf \\
                --log-driver=json-file --log-opt=max-size=500m --log-opt=max-file=3 \\
                --name docs-hgsw -p 1987:1987 \\
                registry.cn-hangzhou.aliyuncs.com/ossrs/hgsw:$SRS_MAJOR
            END
            bash /root/restart_docs-hgsw.sh
            #
            # Cleanup old docker images.
            for image in $(docker images |grep '<none>' |awk '{print $3}'); do
              docker rmi -f $image
              echo "Remove image $image, r0=$?"
            done
    runs-on: ubuntu-20.04

  deploy2:
    name: deploy ossrs.io
    needs:
      - envs
      - aliyun
    steps:
      - name: Covert output to env
        run: |
          echo "SRS_TAG=${{ needs.envs.outputs.SRS_TAG }}" >> $GITHUB_ENV
          echo "SRS_MAJOR=${{ needs.envs.outputs.SRS_MAJOR }}" >> $GITHUB_ENV
          echo "SRS_DROPLET_EIP2=${{ needs.envs.outputs.SRS_DROPLET_EIP2 }}" >> $GITHUB_ENV
      # Execute command in a ssh, because ufw limit the rate.
      - name: Restart the containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SRS_DROPLET_EIP2 }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          port: 22
          envs: SRS_TAG,SRS_MAJOR
          timeout: 60s
          command_timeout: 30m
          script: |
            # Allow access to container.
            ufw allow 1987
            #
            # Restart HGSW
            cat << END > /root/restart_docs-hgsw.sh
              # See https://github.com/winlinvip/http-gif-sls-writer
              docker pull ossrs/hgsw:$SRS_MAJOR
              docker rm -f docs-hgsw || sleep 1
              docker run -d -it --restart always \\
                -v /root/conf/hgsw.conf:/usr/local/etc/main.conf \\
                --log-driver=json-file --log-opt=max-size=500m --log-opt=max-file=3 \\
                --name docs-hgsw -p 1987:1987 ossrs/hgsw:$SRS_MAJOR
            END
            bash /root/restart_docs-hgsw.sh
            #
            # Cleanup old docker images.
            for image in $(docker images |grep '<none>' |awk '{print $3}'); do
              docker rmi -f $image
              echo "Remove image $image, r0=$?"
            done
    runs-on: ubuntu-20.04
